### ISSUE TITLE
configparser.NoSectionError: No section: 'custom'

### ISSUE THREAD

**Issue by dapo8723** [Benature/WordReview#37]
- [ ] 我已阅读[READEME.md](https://github.com/Benature/WordReview/blob/ben/README.md)中的[问题自检](https://github.com/Benature/WordReview/blob/ben/README.md#%E9%97%AE%E9%A2%98%E8%87%AA%E6%A3%80)

**描述问题**
configparser.NoSectionError: No section: 'custom'

**复现问题**
复现问题的步骤:

1. 执行python manage.py makemigrations

```
E:\WordReview\WordReview\WordReview\manage.py:35: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
  t.setDaemon(True)
Traceback (most recent call last):
  File "E:\WordReview\WordReview\WordReview\manage.py", line 88, in <module>
    main()
  File "E:\WordReview\WordReview\WordReview\manage.py", line 84, in main
    execute_from_command_line(sys.argv)
  File "D:\pycharmproject\venv\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "D:\pycharmproject\venv\Lib\site-packages\django\core\management\__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "D:\pycharmproject\venv\Lib\site-packages\django\conf\__init__.py", line 102, in __getattr__
    self._setup(name)
  File "D:\pycharmproject\venv\Lib\site-packages\django\conf\__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pycharmproject\venv\Lib\site-packages\django\conf\__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\WordReview\WordReview\WordReview\WordReview\__init__.py", line 2, in <module>
    if config.get('custom', 'db_type') == 'mysql':
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\configparser.py", line 797, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\configparser.py", line 1168, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'custom'
```

**截图：**（可选）

**操作环境（请提供以下完整数据）：**

- 操作系统：windows
- 使用方式：源码
- 可执行文件版本（若是）：如 0.2.1
- 数据库类型：sqlite
- 浏览器：Chrome

**额外信息：**（可选）  
任何其他的您认为有助于能描述问题/解决问题的信息。

**Comment by Benature** [comment]
复制一份`./config_sample.conf`文件，改名为`./config.conf`。

https://github.com/Benature/WordReview/blob/ben/doc/install.md

**Comment by Benature** [comment]
或者更新下仓库代码，做了新的适配

**Comment by Benature** [comment]
问题与 #33 重复，保留最早的 issue
